spring:
  datasource:
    url: jdbc:mysql://localhost:3306/librarydb?createDatabaseIfNotExist=true
    username: admin
    password: admin
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 3
      maximum-pool-size: 20
      connection-timeout: 172800000
  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: none
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
      poll-interval: 2s
      quiet-period: 1s
  liquibase:
    changeLog: classpath:db/changelog/master-changelog.xml
    enabled: true
  h2:
    console:
      enabled: true
server:
  port: 8080